import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import { FetchExample } from './api/handlers/fetchExample'
import AuthProvider from './context/AuthProvider'
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = await FetchExample()

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />

          <h1>API data retrieve: {data.id}</h1>

          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
